[package]
name = "janus-retproxy"
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]
license = "MPL-2.0"

[lib]
crate_type = ["cdylib"]

[dependencies]
cstr-macro = "0.1.0"
janus-plugin = { git = "https://github.com/mquander/janus-plugin-rs" }
lazy_static = "0.2"
rand = "0.3"
serde_json = "1.0"