[package]
name = "janus-retproxy"
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]

[lib]
crate_type = ["cdylib"]

[dependencies]
cstr-macro = "0.1.0"
janus-plugin = { git = "https://github.com/mquander/janus-plugin-rs" }
jansson-sys = { git = "https://github.com/mquander/janus-plugin-rs" }
lazy_static = "0.2"
uuid = { version = "0.4", features = ["use_std", "v4"] }