[package]
name = "janus-plugin-sfu"
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]
license = "MPL-2.0"
publish = false

[lib]
crate_type = ["cdylib"]

[dependencies]
atom = "0.3.4"
bitflags = "1.0.0"
cstr-macro = "0.1.0"
janus-plugin = "0.3.0"
lazy_static = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"