[package]
name = "janus-plugin-sfu"
description = "Janus SFU for game networking."
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]
license = "MPL-2.0"
publish = false

[lib]
crate_type = ["cdylib"]

[dependencies]
atom = "0.3"
janus-plugin = { version = "0.8.0", features = ["refcount"] }
jsonwebtoken = "4.0"
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"